In [2]:
import pandas as pd
import numpy as np

In [5]:
Product_Details= pd.read_csv(r"C:\Users\venka\Downloads\SQL Project\gold.dim_products.csv")

In [6]:
Product_Details

,product_key,product_id,product_number,product_name,category_id,category,subcategory,maintenance,cost,product_line,start_date
0,1,210,FR-R92B-58,HL Road Frame - Black- 58,CO_RF,Components,Road Frames,Yes,0,Road,7/1/2003
1,2,211,FR-R92R-58,HL Road Frame - Red- 58,CO_RF,Components,Road Frames,Yes,0,Road,7/1/2003
2,3,348,BK-M82B-38,Mountain-100 Black- 38,BI_MB,Bikes,Mountain Bikes,Yes,1898,Mountain,7/1/2011
3,4,349,BK-M82B-42,Mountain-100 Black- 42,BI_MB,Bikes,Mountain Bikes,Yes,1898,Mountain,7/1/2011
4,5,350,BK-M82B-44,Mountain-100 Black- 44,BI_MB,Bikes,Mountain Bikes,Yes,1898,Mountain,7/1/2011
...,...,...,...,...,...,...,...,...,...,...,...
290,291,530,TT-T092,Touring Tire Tube,AC_TT,Accessories,Tires and Tubes,Yes,2,Touring,7/1/2013
291,292,473,VE-C304-L,Classic Vest- L,CL_VE,Clothing,Vests,No,24,Other Sales,7/1/2013
292,293,472,VE-C304-M,Classic Vest- M,CL_VE,Clothing,Vests,No,24,Other Sales,7/1/2013
293,294,471,VE-C304-S,Classic Vest- S,CL_VE,Clothing,Vests,No,24,Other Sales,7/1/2013
294,295,477,WB-H098,Water Bottle - 30 oz.,AC_BC,Accessories,Bottles and Cages,No,2,Other Sales,7/1/2013

In [7]:
Product_Details.head()

,product_key,product_id,product_number,product_name,category_id,category,subcategory,maintenance,cost,product_line,start_date
0,1,210,FR-R92B-58,HL Road Frame - Black- 58,CO_RF,Components,Road Frames,Yes,0,Road,7/1/2003
1,2,211,FR-R92R-58,HL Road Frame - Red- 58,CO_RF,Components,Road Frames,Yes,0,Road,7/1/2003
2,3,348,BK-M82B-38,Mountain-100 Black- 38,BI_MB,Bikes,Mountain Bikes,Yes,1898,Mountain,7/1/2011
3,4,349,BK-M82B-42,Mountain-100 Black- 42,BI_MB,Bikes,Mountain Bikes,Yes,1898,Mountain,7/1/2011
4,5,350,BK-M82B-44,Mountain-100 Black- 44,BI_MB,Bikes,Mountain Bikes,Yes,1898,Mountain,7/1/2011

In [9]:
Product_Details.shape

(295, 11)

In [10]:
Product_Details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 295 entries, 0 to 294
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_key     295 non-null    int64
 1   product_id      295 non-null    int64
 2   product_number  295 non-null    object
 3   product_name    295 non-null    object
 4   category_id     295 non-null    object
 5   category        288 non-null    object
 6   subcategory     288 non-null    object
 7   maintenance     288 non-null    object
 8   cost            295 non-null    int64
 9   product_line    278 non-null    object
 10  start_date      295 non-null    object
dtypes: int64(3), object(8)
memory usage: 25.5+ KB

In [11]:
Product_Details.columns = (
    Product_Details.columns
    .str.strip()
    .str.lower()
    .str.replace(" ","_")
)

In [12]:
Product_Details

,product_key,product_id,product_number,product_name,category_id,category,subcategory,maintenance,cost,product_line,start_date
0,1,210,FR-R92B-58,HL Road Frame - Black- 58,CO_RF,Components,Road Frames,Yes,0,Road,7/1/2003
1,2,211,FR-R92R-58,HL Road Frame - Red- 58,CO_RF,Components,Road Frames,Yes,0,Road,7/1/2003
2,3,348,BK-M82B-38,Mountain-100 Black- 38,BI_MB,Bikes,Mountain Bikes,Yes,1898,Mountain,7/1/2011
3,4,349,BK-M82B-42,Mountain-100 Black- 42,BI_MB,Bikes,Mountain Bikes,Yes,1898,Mountain,7/1/2011
4,5,350,BK-M82B-44,Mountain-100 Black- 44,BI_MB,Bikes,Mountain Bikes,Yes,1898,Mountain,7/1/2011
...,...,...,...,...,...,...,...,...,...,...,...
290,291,530,TT-T092,Touring Tire Tube,AC_TT,Accessories,Tires and Tubes,Yes,2,Touring,7/1/2013
291,292,473,VE-C304-L,Classic Vest- L,CL_VE,Clothing,Vests,No,24,Other Sales,7/1/2013
292,293,472,VE-C304-M,Classic Vest- M,CL_VE,Clothing,Vests,No,24,Other Sales,7/1/2013
293,294,471,VE-C304-S,Classic Vest- S,CL_VE,Clothing,Vests,No,24,Other Sales,7/1/2013
294,295,477,WB-H098,Water Bottle - 30 oz.,AC_BC,Accessories,Bottles and Cages,No,2,Other Sales,7/1/2013

In [13]:
Product_Details.isnull().sum()

product_key        0
product_id         0
product_number     0
product_name       0
category_id        0
category           7
subcategory        7
maintenance        7
cost               0
product_line      17
start_date         0
dtype: int64

In [15]:
cols_with_nulls = ['category', 'subcategory', 'maintenance', 'product_line'] #list of missing value columns
#filling missing value with unknown
Product_Details[cols_with_nulls] = Product_Details[cols_with_nulls].fillna("Unknown")

In [16]:
Product_Details.isnull().sum()

product_key       0
product_id        0
product_number    0
product_name      0
category_id       0
category          0
subcategory       0
maintenance       0
cost              0
product_line      0
start_date        0
dtype: int64

In [17]:
Product_Details

,product_key,product_id,product_number,product_name,category_id,category,subcategory,maintenance,cost,product_line,start_date
0,1,210,FR-R92B-58,HL Road Frame - Black- 58,CO_RF,Components,Road Frames,Yes,0,Road,7/1/2003
1,2,211,FR-R92R-58,HL Road Frame - Red- 58,CO_RF,Components,Road Frames,Yes,0,Road,7/1/2003
2,3,348,BK-M82B-38,Mountain-100 Black- 38,BI_MB,Bikes,Mountain Bikes,Yes,1898,Mountain,7/1/2011
3,4,349,BK-M82B-42,Mountain-100 Black- 42,BI_MB,Bikes,Mountain Bikes,Yes,1898,Mountain,7/1/2011
4,5,350,BK-M82B-44,Mountain-100 Black- 44,BI_MB,Bikes,Mountain Bikes,Yes,1898,Mountain,7/1/2011
...,...,...,...,...,...,...,...,...,...,...,...
290,291,530,TT-T092,Touring Tire Tube,AC_TT,Accessories,Tires and Tubes,Yes,2,Touring,7/1/2013
291,292,473,VE-C304-L,Classic Vest- L,CL_VE,Clothing,Vests,No,24,Other Sales,7/1/2013
292,293,472,VE-C304-M,Classic Vest- M,CL_VE,Clothing,Vests,No,24,Other Sales,7/1/2013
293,294,471,VE-C304-S,Classic Vest- S,CL_VE,Clothing,Vests,No,24,Other Sales,7/1/2013
294,295,477,WB-H098,Water Bottle - 30 oz.,AC_BC,Accessories,Bottles and Cages,No,2,Other Sales,7/1/2013

In [18]:
Product_Details.to_csv("cleaned_product_details.csv", index=False)