In [1]:
import pandas as pd

In [3]:
Sales_details = pd.read_csv(r"C:\Users\venka\Downloads\SQL Project\gold.fact_sales.csv")

In [4]:
Sales_details

,order_number,product_key,customer_key,order_date,shipping_date,due_date,sales_amount,quantity,price
0,SO54496,282,5400,3/16/2013,3/23/2013,3/28/2013,25,1,25
1,SO54496,289,5400,3/16/2013,3/23/2013,3/28/2013,5,1,5
2,SO54496,259,5400,3/16/2013,3/23/2013,3/28/2013,2,1,2
3,SO54497,174,9281,3/16/2013,3/23/2013,3/28/2013,22,1,22
4,SO54497,280,9281,3/16/2013,3/23/2013,3/28/2013,9,1,9
...,...,...,...,...,...,...,...,...,...
60393,SO54494,259,11279,3/16/2013,3/23/2013,3/28/2013,2,1,2
60394,SO54495,289,3750,3/16/2013,3/23/2013,3/28/2013,5,1,5
60395,SO54495,244,3750,3/16/2013,3/23/2013,3/28/2013,35,1,35
60396,SO54495,248,3750,3/16/2013,3/23/2013,3/28/2013,50,1,50
60397,SO54495,166,3750,3/16/2013,3/23/2013,3/28/2013,9,1,9

In [5]:
Sales_details.head()

,order_number,product_key,customer_key,order_date,shipping_date,due_date,sales_amount,quantity,price
0,SO54496,282,5400,3/16/2013,3/23/2013,3/28/2013,25,1,25
1,SO54496,289,5400,3/16/2013,3/23/2013,3/28/2013,5,1,5
2,SO54496,259,5400,3/16/2013,3/23/2013,3/28/2013,2,1,2
3,SO54497,174,9281,3/16/2013,3/23/2013,3/28/2013,22,1,22
4,SO54497,280,9281,3/16/2013,3/23/2013,3/28/2013,9,1,9

In [6]:
Sales_details.shape

(60398, 9)

In [7]:
Sales_details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60398 entries, 0 to 60397
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_number   60398 non-null  object
 1   product_key    60398 non-null  int64
 2   customer_key   60398 non-null  int64
 3   order_date     60379 non-null  object
 4   shipping_date  60398 non-null  object
 5   due_date       60398 non-null  object
 6   sales_amount   60398 non-null  int64
 7   quantity       60398 non-null  int64
 8   price          60398 non-null  int64
dtypes: int64(5), object(4)
memory usage: 4.1+ MB

In [8]:
Sales_details.isnull().sum()

order_number      0
product_key       0
customer_key      0
order_date       19
shipping_date     0
due_date          0
sales_amount      0
quantity          0
price             0
dtype: int64

In [9]:
Sales_details = Sales_details.dropna(subset=['order_date'])

In [10]:
Sales_details.isnull().sum()

order_number     0
product_key      0
customer_key     0
order_date       0
shipping_date    0
due_date         0
sales_amount     0
quantity         0
price            0
dtype: int64

In [11]:
Sales_details

,order_number,product_key,customer_key,order_date,shipping_date,due_date,sales_amount,quantity,price
0,SO54496,282,5400,3/16/2013,3/23/2013,3/28/2013,25,1,25
1,SO54496,289,5400,3/16/2013,3/23/2013,3/28/2013,5,1,5
2,SO54496,259,5400,3/16/2013,3/23/2013,3/28/2013,2,1,2
3,SO54497,174,9281,3/16/2013,3/23/2013,3/28/2013,22,1,22
4,SO54497,280,9281,3/16/2013,3/23/2013,3/28/2013,9,1,9
...,...,...,...,...,...,...,...,...,...
60393,SO54494,259,11279,3/16/2013,3/23/2013,3/28/2013,2,1,2
60394,SO54495,289,3750,3/16/2013,3/23/2013,3/28/2013,5,1,5
60395,SO54495,244,3750,3/16/2013,3/23/2013,3/28/2013,35,1,35
60396,SO54495,248,3750,3/16/2013,3/23/2013,3/28/2013,50,1,50
60397,SO54495,166,3750,3/16/2013,3/23/2013,3/28/2013,9,1,9

In [12]:
Sales_details.to_csv("Cleaned_Sales_Details.csv", index=False)